export const projects = [
  {
    id: "admiro",
    title: "AdMiro",
    eyebrow: "digital signage control",
    description:
      "A full-stack advertisement management system for centralized screen control, flexible scheduling, real-time content rotation, and device management.",
    image: "/thumbnails/admiro.webp",
    codeUrl: "https://github.com/HemanthTenneti/AdMiro",
    hostedUrl: "https://admiro-app.vercel.app",
    hostedLabel: "Live app",
    tags: ["full-stack", "scheduling", "devices"],
    metrics: ["playlist builder", "screen pairing", "real-time rotation"],
  },
  {
    id: "vyapaar-india",
    title: "Vyapaar India",
    eyebrow: "classifieds backend",
    description:
      "A backend-driven classifieds platform focused on scalable business listings, category discovery, structured data, authentication, and fast retrieval.",
    image: "/thumbnails/vyapaarindia.webp",
    hostedUrl: "https://vyapaarindia.in",
    hostedLabel: "Live site",
    tags: ["backend", "marketplace", "search"],
    metrics: ["listing management", "query performance", "auth flows"],
  },
  {
    id: "file-sorter",
    title: "File Sorter",
    eyebrow: "desktop automation",
    description:
      "An extension-based file organization tool that automates folder cleanup through a minimal interface and predictable sorting rules.",
    image: "/thumbnails/filesorter.webp",
    codeUrl: "https://github.com/HemanthTenneti/FileSorter",
    hostedUrl: "https://github.com/HemanthTenneti/FileSorter",
    hostedLabel: "Repo",
    tags: ["automation", "productivity", "files"],
    metrics: ["extension mapping", "folder cleanup", "minimal UI"],
  },
  {
    id: "whtrapp",
    title: "whtrapp",
    eyebrow: "weather interface",
    description:
      "A sleek, minimal weather site that presents precise forecasts and essential weather data without visual clutter.",
    codeUrl: "https://github.com/HemanthTenneti/whtrapp.github.io",
    hostedUrl: "https://whtrapp.github.io/",
    hostedLabel: "Live site",
    visualType: "weather",
    tags: ["weather", "web app", "minimal ui"],
    metrics: ["forecast display", "clean data layout", "lightweight frontend"],
  },
  {
    id: "customer-churn-prediction",
    title: "Customer Churn Prediction",
    eyebrow: "telecom retention system",
    description:
      "A GenAI-powered customer retention workflow that combines churn prediction, risk explanation, and personalized intervention guidance.",
    image: "/data-thumbnails/customer-churn-space.webp",
    codeUrl: "https://github.com/HemanthTenneti/CustomerChurnPredictor",
    codeLabel: "GitHub",
    hostedUrl: "https://huggingface.co/spaces/hemanth10etii/customer-churn-prediction",
    hostedLabel: "Hugging Face",
    visualType: "ai",
    tags: ["gradio", "ml", "rag"],
    metrics: ["LogReg model", "LangGraph agent", "ChromaDB / Groq"],
    assets: [
      {
        type: "image",
        title: "Hugging Face space",
        href: "/data-thumbnails/customer-churn-space.webp",
        caption: "interactive retention dashboard",
      },
      {
        type: "repo",
        title: "prediction repository",
        href: "https://github.com/HemanthTenneti/CustomerChurnPredictor",
        caption: "model, agent, and app source",
      },
      {
        type: "space",
        title: "live demo",
        href: "https://huggingface.co/spaces/hemanth10etii/customer-churn-prediction",
        caption: "deployed Gradio interface",
      },
    ],
  },
];
